version: "3"

services:
  server:
    image: media-center-server
    volumes:
      - ./data:/data
      - ./data/disk:/disk
    ports:
      - "8080:8080"
    environment:
      AVAILABLE_USERS: "User1,User2"
      SERVER_PASSWORD: "somerandompassword"

      DI_DATABASE: filesystem
      DI_TORRENT_INDEXER: yggTorrent
      DI_TORRENT_CLIENT: mock
      DI_TMDB_API: real
      TMDB_API_KEY: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YTZiMDIxZTE5Y2YxOTljMTM1NGFhMGRiMDZiOTkzMiIsInN1YiI6IjY0ODYzYWRmMDI4ZjE0MDExZTU1MDkwMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.yyMkZlhGOGBHtw1yvpBVUUHhu7IKVYho49MvNNKt_wY

      FILESYSTEM_STORE_DIR: /data/database
      FILE_WATCHER_MOVIE_DIR: /disk/films
      FILE_WATCHER_SHOW_DIR: /disk/series

      DELUGE_ENDPOINT: https://deluge.yooooomi.com
      DELUGE_PASSWORD: deluge
      DELUGE_MOVIE_LOCATION: /disk/films
      DELUGE_SHOW_LOCATION: /disk/series

      FLARESOLVERR_ENDPOINT: http://flaresolverr:8191
      FLARESOLVERR_SESSION_TIMEOUT_S: 600

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - "8191:8191"
    restart: unless-stopped
