import { TmdbAPI } from "../applicative/tmdb.api";
import { AnyTmdb } from "../domain/anyTmdb";
import { Movie } from "../domain/movie";
import { Show } from "../domain/show";
import { TmdbId } from "../domain/tmdbId";

export class MockTmdbAPI extends TmdbAPI {
  async search(query: string): Promise<AnyTmdb[]> {
    return [
      new Movie(
        TmdbId.fromIdAndType("976573", "movie"),
        false,
        "/jZIYaISP3GBSrVOPfrp98AMa8Ng.jpg",
        "en",
        "Elemental",
        "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
        4696.546,
        "/6oH378KUfCEitzJkm07r97L0RsZ.jpg",
        "2023-06-14",
        "Elemental",
        false,
        7.8,
        1050
      ),
    ];
  }

  async get(tmdbId: TmdbId) {
    return new Movie(
      tmdbId,
      false,
      "/jZIYaISP3GBSrVOPfrp98AMa8Ng.jpg",
      "en",
      "Elemental",
      "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
      4696.546,
      "/6oH378KUfCEitzJkm07r97L0RsZ.jpg",
      "2023-06-14",
      "Elemental",
      false,
      7.8,
      1050
    );
  }

  async discoverShow(): Promise<Show[]> {
    const mock = {
      page: 1,
      results: [
        {
          backdrop_path: "/oOce9hLMVFubjAJliau4kiSNPnW.jpg",
          first_air_date: "1990-09-13",
          genre_ids: [80, 18],
          id: 549,
          name: "Law & Order",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Law & Order",
          overview:
            "In cases ripped from the headlines, police investigate serious and often deadly crimes, weighing the evidence and questioning the suspects until someone is taken into custody. The district attorney's office then builds a case to convict the perpetrator by proving the person guilty beyond a reasonable doubt. Working together, these expert teams navigate all sides of the complex criminal justice system to make New York a safer place.",
          popularity: 4495.043,
          poster_path: "/77OPlbsvX3pzoFbyfpcE3GXMCod.jpg",
          vote_average: 7.6,
          vote_count: 435,
        },
        {
          backdrop_path: "/9xxLWtnFxkpJ2h1uthpvCRK6vta.jpg",
          first_air_date: "1999-09-20",
          genre_ids: [80, 18, 9648],
          id: 2734,
          name: "Law & Order: Special Victims Unit",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Law & Order: Special Victims Unit",
          overview:
            "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
          popularity: 4061.4,
          poster_path: "/ywBt4WKADdMVgxTR1rS2uFwMYTH.jpg",
          vote_average: 8,
          vote_count: 3343,
        },
        {
          backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
          first_air_date: "1952-12-26",
          genre_ids: [10763],
          id: 94722,
          name: "Tagesschau",
          origin_country: ["DE"],
          original_language: "de",
          original_name: "Tagesschau",
          overview:
            "German daily news program, the oldest still existing program on German television.",
          popularity: 3420.692,
          poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
          vote_average: 7.5,
          vote_count: 123,
        },
        {
          backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
          first_air_date: "2022-11-02",
          genre_ids: [18],
          id: 213713,
          name: "Faltu",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "Faltu",
          overview:
            "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
          popularity: 3021.017,
          poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
          vote_average: 7.1,
          vote_count: 123,
        },
        {
          backdrop_path: null,
          first_air_date: "2022-11-28",
          genre_ids: [18],
          id: 215315,
          name: "Rabb Se Hai Dua",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "रब्ब से है दुआ",
          overview:
            "Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.",
          popularity: 2925.612,
          poster_path: "/6ikbefd7VeopbBuGgioYMNU5bQj.jpg",
          vote_average: 6.8,
          vote_count: 78,
        },
        {
          backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
          first_air_date: "2023-01-04",
          genre_ids: [18, 10751],
          id: 215103,
          name: "Teri Meri Doriyaann",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "तेरी मेरी डोरियाँ",
          overview:
            "It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.",
          popularity: 2867.769,
          poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
          vote_average: 7.2,
          vote_count: 104,
        },
        {
          backdrop_path: "/jtAh65bX9Ydy2NFkwTN6V9WSzWb.jpg",
          first_air_date: "2023-02-07",
          genre_ids: [18],
          id: 220525,
          name: "Maitree",
          origin_country: [],
          original_language: "hi",
          original_name: "मैत्री",
          overview: "",
          popularity: 2485.117,
          poster_path: "/k57vsZ5Pl80WRR02ahgC3QLdhhL.jpg",
          vote_average: 7.7,
          vote_count: 34,
        },
        {
          backdrop_path: "/x4lxFIhhrDI4nWtV8osnYwbGESV.jpg",
          first_air_date: "2009-09-23",
          genre_ids: [35],
          id: 1421,
          name: "Modern Family",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Modern Family",
          overview:
            "The Pritchett-Dunphy-Tucker clan is a wonderfully large and blended family. They give us an honest and often hilarious look into the sometimes warm, sometimes twisted, embrace of the modern family.",
          popularity: 2338.408,
          poster_path: "/fCiOen2bpru5JhzlaNkaNWNd9eP.jpg",
          vote_average: 7.8,
          vote_count: 2295,
        },
        {
          backdrop_path: "/m0TiLZ79RR19Zz0AZruQSBeH39x.jpg",
          first_air_date: "2019-07-09",
          genre_ids: [10764],
          id: 90521,
          name: "Love Island",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Love Island",
          overview:
            "American version of the British dating reality competition in which ten singles come to stay in a villa for a few weeks and have to couple up with one another. Over the course of those weeks, they face the public vote and might be eliminated from the show. Other islanders join and try to break up the couples.",
          popularity: 2297.038,
          poster_path: "/kU2y21cls8WargMaX7KI47URMjD.jpg",
          vote_average: 7.4,
          vote_count: 116,
        },
        {
          backdrop_path: "/kdF7ZTktLHVVhAhI90uuzqlZqJI.jpg",
          first_air_date: "2023-06-06",
          genre_ids: [18],
          id: 228093,
          name: "Titlie",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "Titlie",
          overview:
            "Obsessed by the notion of fairy tale love , Titlie marries her beau Garv . Soon , the picture - perfect romance turns abusive , forcing her to wrestle with reality .",
          popularity: 2092.369,
          poster_path: "/5kZi1LCFugNAeDCWOF3ornGNm2W.jpg",
          vote_average: 7.8,
          vote_count: 80,
        },
        {
          backdrop_path: null,
          first_air_date: "2022-12-19",
          genre_ids: [],
          id: 227017,
          name: "YHC: 2nd Generation",
          origin_country: ["US"],
          original_language: "en",
          original_name: "YHC: 2nd Generation",
          overview:
            "When destiny brings a reserved physiotherapist, Dr Nayantara and a famous rockstar Samrat together, will love blossom between them?",
          popularity: 2090.568,
          poster_path: null,
          vote_average: 5.7,
          vote_count: 3,
        },
        {
          backdrop_path: "/wq269s8vzr8xrwrIALtl4UfmN6X.jpg",
          first_air_date: "2023-06-12",
          genre_ids: [],
          id: 228627,
          name: "Do Dil Mil Rahe Hai",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "Do Dil Mil Rahe Hai",
          overview:
            "He repels love , she resembles it ! Rishi and Pihu are worlds apart but unaware of the past that connects them . Will fate lead the duo down the road to true love ?",
          popularity: 2012.761,
          poster_path: "/juYg1PQzCmDJYyGtrW0Xbvke1jx.jpg",
          vote_average: 7.2,
          vote_count: 60,
        },
        {
          backdrop_path: "/5e1MxLWTJh6n4qtYz0vlevOK6qW.jpg",
          first_air_date: "2023-07-03",
          genre_ids: [18],
          id: 229932,
          name: "Pyaar Ka Pehla Adhyaya  - Shiv Shakti",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "Pyaar Ka Pehla Adhyaya  - Shiv Shakti",
          overview:
            "Shiv has a rewarding career as a doctor, but his personal life is in tatters. Shakti, an orphan, is a nurturer by nature. Will Shakti heal a broken Shiv?",
          popularity: 1978.179,
          poster_path: "/jHK9bCDefHq43cHvMVUM7SLumYF.jpg",
          vote_average: 8.1,
          vote_count: 45,
        },
        {
          backdrop_path: "/e9n87p3Ax67spq3eUgLB6rjIEow.jpg",
          first_air_date: "2005-09-13",
          genre_ids: [80, 18],
          id: 1911,
          name: "Bones",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Bones",
          overview:
            "Dr. Temperance Brennan and her colleagues at the Jeffersonian's Medico-Legal Lab assist Special Agent Seeley Booth with murder investigations when the remains are so badly decomposed, burned or destroyed that the standard identification methods are useless.",
          popularity: 1895.61,
          poster_path: "/eyTu5c8LniVciRZIOSHTvvkkgJa.jpg",
          vote_average: 8.3,
          vote_count: 2852,
        },
        {
          backdrop_path: "/aplztf8fotkLOnwBM0bNfNmlxSo.jpg",
          first_air_date: "1977-09-24",
          genre_ids: [18, 35],
          id: 1823,
          name: "The Love Boat",
          origin_country: ["US"],
          original_language: "en",
          original_name: "The Love Boat",
          overview:
            'Passengers who search for romantic nights aboard a beautiful ship travelling to tropical or mysterious countries, decide to pass their vacation aboard the "Love Boat", where Gopher, Dr. Bricker, Isaac, Julie, and Captain Stubing try their best to please them, and sometimes help them fall in love. Things are not always so easy, but in the end, love wins.',
          popularity: 1832.335,
          poster_path: "/fnsnazlj2bt3Fuj0pJ7wBPmuMLO.jpg",
          vote_average: 6.3,
          vote_count: 147,
        },
        {
          backdrop_path: "/xXRsKNJHTOGrs5wfYAxkbM2RiyT.jpg",
          first_air_date: "2017-09-25",
          genre_ids: [18],
          id: 71712,
          name: "The Good Doctor",
          origin_country: ["US"],
          original_language: "en",
          original_name: "The Good Doctor",
          overview:
            "Shaun Murphy, a young surgeon with autism and savant syndrome, relocates from a quiet country life to join a prestigious hospital's surgical unit. Unable to personally connect with those around him, Shaun uses his extraordinary medical gifts to save lives and challenge the skepticism of his colleagues.",
          popularity: 1682.637,
          poster_path: "/luhKkdD80qe62fwop6sdrXK9jUT.jpg",
          vote_average: 8.5,
          vote_count: 11670,
        },
        {
          backdrop_path: "/yYNa1nqvNK94xZz3eKyfvZdAvPi.jpg",
          first_air_date: "2020-11-02",
          genre_ids: [10766],
          id: 112470,
          name: "Here it all begins",
          origin_country: ["FR"],
          original_language: "fr",
          original_name: "Ici tout commence",
          overview: "",
          popularity: 1577.23,
          poster_path: "/60cqjI590JKXCAABqCStVmSBGET.jpg",
          vote_average: 6.7,
          vote_count: 23,
        },
        {
          backdrop_path: "/7xIQL3eyNmQjZTJjzlsmzRUjAEx.jpg",
          first_air_date: "2005-02-06",
          genre_ids: [16, 35],
          id: 1433,
          name: "American Dad!",
          origin_country: ["US"],
          original_language: "en",
          original_name: "American Dad!",
          overview:
            "The series focuses on an eccentric motley crew that is the Smith family and their three housemates: Father, husband, and breadwinner Stan Smith; his better half housewife, Francine Smith; their college-aged daughter, Hayley Smith; and their high-school-aged son, Steve Smith. Outside of the Smith family, there are three additional main characters, including Hayley's boyfriend turned husband, Jeff Fischer; the family's man-in-a-goldfish-body pet, Klaus; and most notably the family's zany alien, Roger, who is \"full of masquerades, brazenness, and shocking antics.\"",
          popularity: 1509.904,
          poster_path: "/xnFFz3etm1vftF0ns8RMHA8XdqT.jpg",
          vote_average: 6.9,
          vote_count: 1832,
        },
        {
          backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
          first_air_date: "2021-08-03",
          genre_ids: [10766],
          id: 130542,
          name: "Bhagya Lakshmi",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "Bhagya Lakshmi",
          overview:
            "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
          popularity: 1425.207,
          poster_path: "/eVaGfVPA85AUrCAQoOLb0kY2SZA.jpg",
          vote_average: 5.8,
          vote_count: 103,
        },
        {
          backdrop_path: "/wJmcuxa0C4AERmA9mejxm9qRYDj.jpg",
          first_air_date: "2022-06-06",
          genre_ids: [80, 9648],
          id: 203504,
          name: "Aashiqana",
          origin_country: ["IN"],
          original_language: "hi",
          original_name: "आशिकाना",
          overview:
            "A serial killer sparks the story of uptight Yashvardhan and feisty Chikki. Plagued by misunderstandings, how far do they have to go to nab the murderer?",
          popularity: 1379.477,
          poster_path: "/a4Z6Uohb6Ln5vcPvMUzwyn3WBjP.jpg",
          vote_average: 6.5,
          vote_count: 31,
        },
      ],
      total_pages: 7690,
      total_results: 153785,
    };

    return mock.results.map(
      (d) =>
        new Show(
          TmdbId.fromIdAndType(d.id.toString(), "show"),
          d.backdrop_path,
          d.original_language,
          d.original_name,
          d.overview,
          d.popularity,
          d.poster_path,
          d.first_air_date,
          d.name,
          d.vote_average,
          d.vote_count,
          0
        )
    );
  }

  async discoverMovie() {
    const mock = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/jZIYaISP3GBSrVOPfrp98AMa8Ng.jpg",
          genre_ids: [16, 35, 10751, 14, 10749],
          id: 976573,
          original_language: "en",
          original_title: "Elemental",
          overview:
            "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
          popularity: 4696.546,
          poster_path: "/6oH378KUfCEitzJkm07r97L0RsZ.jpg",
          release_date: "2023-06-14",
          title: "Elemental",
          video: false,
          vote_average: 7.8,
          vote_count: 1050,
        },
        {
          adult: false,
          backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
          genre_ids: [16, 28, 12, 878],
          id: 569094,
          original_language: "en",
          original_title: "Spider-Man: Across the Spider-Verse",
          overview:
            "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
          popularity: 2517.658,
          poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
          release_date: "2023-05-31",
          title: "Spider-Man: Across the Spider-Verse",
          video: false,
          vote_average: 8.5,
          vote_count: 3512,
        },
        {
          adult: false,
          backdrop_path: "/rRcNmiH55Tz0ugUsDUGmj8Bsa4V.jpg",
          genre_ids: [35, 10749],
          id: 884605,
          original_language: "en",
          original_title: "No Hard Feelings",
          overview:
            "On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to “date” their introverted 19-year-old son, Percy, before he leaves for college. To her surprise, Maddie soon discovers the awkward Percy is no sure thing.",
          popularity: 1812.181,
          poster_path: "/4K7gQjD19CDEPd7A9KZwr2D9Nco.jpg",
          release_date: "2023-06-15",
          title: "No Hard Feelings",
          video: false,
          vote_average: 7.1,
          vote_count: 662,
        },
        {
          adult: false,
          backdrop_path: "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
          genre_ids: [35, 12, 14],
          id: 346698,
          original_language: "en",
          original_title: "Barbie",
          overview:
            "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
          popularity: 1748.951,
          poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
          release_date: "2023-07-19",
          title: "Barbie",
          video: false,
          vote_average: 7.4,
          vote_count: 3132,
        },
        {
          adult: false,
          backdrop_path: "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
          genre_ids: [28, 12, 878],
          id: 667538,
          original_language: "en",
          original_title: "Transformers: Rise of the Beasts",
          overview:
            "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
          popularity: 1691.784,
          poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
          release_date: "2023-06-06",
          title: "Transformers: Rise of the Beasts",
          video: false,
          vote_average: 7.5,
          vote_count: 2814,
        },
        {
          adult: false,
          backdrop_path: "/zN41DPmPhwmgJjHwezALdrdvD0h.jpg",
          genre_ids: [28, 878, 27],
          id: 615656,
          original_language: "en",
          original_title: "Meg 2: The Trench",
          overview:
            "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
          popularity: 1424.145,
          poster_path: "/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg",
          release_date: "2023-08-02",
          title: "Meg 2: The Trench",
          video: false,
          vote_average: 7,
          vote_count: 480,
        },
        {
          adult: false,
          backdrop_path: "/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
          genre_ids: [28, 12, 878],
          id: 298618,
          original_language: "en",
          original_title: "The Flash",
          overview:
            "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
          popularity: 1377.709,
          poster_path: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
          release_date: "2023-06-13",
          title: "The Flash",
          video: false,
          vote_average: 7,
          vote_count: 2353,
        },
        {
          adult: false,
          backdrop_path: "/xVMtv55caCEvBaV83DofmuZybmI.jpg",
          genre_ids: [53, 28],
          id: 724209,
          original_language: "en",
          original_title: "Heart of Stone",
          overview:
            "An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable — and dangerous — weapon.",
          popularity: 1851.905,
          poster_path: "/vB8o2p4ETnrfiWEgVxHmHWP9yRl.jpg",
          release_date: "2023-08-09",
          title: "Heart of Stone",
          video: false,
          vote_average: 7,
          vote_count: 502,
        },
        {
          adult: false,
          backdrop_path: "/hPcP1kv6vrkRmQO3YgV1H97FE5Q.jpg",
          genre_ids: [27, 9648, 53],
          id: 614479,
          original_language: "en",
          original_title: "Insidious: The Red Door",
          overview:
            "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before, facing their family's dark past and a host of new and more horrifying terrors that lurk behind the red door.",
          popularity: 1147.176,
          poster_path: "/d07phJqCx6z5wILDYqkyraorDPi.jpg",
          release_date: "2023-07-05",
          title: "Insidious: The Red Door",
          video: false,
          vote_average: 6.9,
          vote_count: 872,
        },
        {
          adult: false,
          backdrop_path: "/bz66a19bR6BKsbY8gSZCM4etJiK.jpg",
          genre_ids: [28, 27, 53],
          id: 1006462,
          original_language: "en",
          original_title: "The Flood",
          overview:
            "A horde of giant hungry alligators is unleashed on a group of in-transit prisoners and their guards after a massive hurricane floods Louisiana.",
          popularity: 1218.229,
          poster_path: "/mvjqqklMpHwOxc40rn7dMhGT0Fc.jpg",
          release_date: "2023-07-14",
          title: "The Flood",
          video: false,
          vote_average: 6.9,
          vote_count: 131,
        },
        {
          adult: false,
          backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
          genre_ids: [28, 80, 53],
          id: 385687,
          original_language: "en",
          original_title: "Fast X",
          overview:
            "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
          popularity: 1058.63,
          poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
          release_date: "2023-05-17",
          title: "Fast X",
          video: false,
          vote_average: 7.3,
          vote_count: 3384,
        },
        {
          adult: false,
          backdrop_path: "/AioRI7M077BBR33VimFiyFop2Rc.jpg",
          genre_ids: [28, 12, 53],
          id: 1149381,
          original_language: "pl",
          original_title: "Operacja: Soulcatcher",
          overview:
            "A military contractor hired to seize a weapon that turns people into savage killers seeks revenge when his brother falls victim to the device.",
          popularity: 974.975,
          poster_path: "/l1f9JSPjCfNftigEii1SDK1g2b3.jpg",
          release_date: "2023-08-02",
          title: "Soulcatcher",
          video: false,
          vote_average: 6.5,
          vote_count: 110,
        },
        {
          adult: false,
          backdrop_path: "/znUYFf0Sez5lUmxPr3Cby7TVJ6c.jpg",
          genre_ids: [12, 10751, 14, 10749],
          id: 447277,
          original_language: "en",
          original_title: "The Little Mermaid",
          overview:
            "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.",
          popularity: 995.875,
          poster_path: "/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
          release_date: "2023-05-18",
          title: "The Little Mermaid",
          video: false,
          vote_average: 6.5,
          vote_count: 1631,
        },
        {
          adult: false,
          backdrop_path: "/6IafiYxaqR2MxCnEC29bi6637eo.jpg",
          genre_ids: [28, 12, 53, 35],
          id: 457332,
          original_language: "en",
          original_title: "Hidden Strike",
          overview:
            "Two elite soldiers must escort civilians through a gauntlet of gunfire and explosions.",
          popularity: 856.808,
          poster_path: "/zsbolOkw8RhTU4DKOrpf4M7KCmi.jpg",
          release_date: "2023-07-06",
          title: "Hidden Strike",
          video: false,
          vote_average: 7.1,
          vote_count: 573,
        },
        {
          adult: false,
          backdrop_path: "/aEVYGOIrhWDrNoZxVhhSazmRjeR.jpg",
          genre_ids: [35, 27, 28],
          id: 1070514,
          original_language: "ja",
          original_title: "ゾン100～ゾンビになるまでにしたい100のこと～",
          overview:
            "Bullied by his boss, worked around the clock, he's nothing more than a corporate drone. All it takes is a zombie outbreak for him to finally feel alive!",
          popularity: 791.565,
          poster_path: "/kD35dB3KOHrLo1Y3RU5xXJ1hI7.jpg",
          release_date: "2023-08-03",
          title: "Zom 100: Bucket List of the Dead",
          video: false,
          vote_average: 6.6,
          vote_count: 209,
        },
        {
          adult: false,
          backdrop_path: "/7drO1kYgQ0PnnU87sAnBEphYrSM.jpg",
          genre_ids: [16, 28, 27],
          id: 1083862,
          original_language: "ja",
          original_title: "バイオハザード：デスアイランド",
          overview:
            "In San Francisco, Jill Valentine is dealing with a zombie outbreak and a new T-Virus, Leon Kennedy is on the trail of a kidnapped DARPA scientist, and Claire Redfield is investigating a monstrous fish that is killing whales in the bay. Joined by Chris Redfield and Rebecca Chambers, they discover the trail of clues from their separate cases all converge on the same location, Alcatraz Island, where a new evil has taken residence and awaits their arrival.",
          popularity: 740.46,
          poster_path: "/qayga07ICNDswm0cMJ8P3VwklFZ.jpg",
          release_date: "2023-06-22",
          title: "Resident Evil: Death Island",
          video: false,
          vote_average: 7.7,
          vote_count: 550,
        },
        {
          adult: false,
          backdrop_path: "/csz3oWxd04wgXUzenXgenIVwXGl.jpg",
          genre_ids: [35, 10749],
          id: 930094,
          original_language: "en",
          original_title: "Red, White & Royal Blue",
          overview:
            "After an altercation between Alex, the president's son, and Britain's Prince Henry at a royal event becomes tabloid fodder, their long-running feud now threatens to drive a wedge in U.S./British relations. When the rivals are forced into a staged truce, their icy relationship begins to thaw and the friction between them sparks something deeper than they ever expected.",
          popularity: 727.969,
          poster_path: "/uffOY4W354o9RTRmercFyVvl56Z.jpg",
          release_date: "2023-07-27",
          title: "Red, White & Royal Blue",
          video: false,
          vote_average: 8.3,
          vote_count: 457,
        },
        {
          adult: false,
          backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
          genre_ids: [878, 12, 28],
          id: 447365,
          original_language: "en",
          original_title: "Guardians of the Galaxy Vol. 3",
          overview:
            "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
          popularity: 773.261,
          poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
          release_date: "2023-05-03",
          title: "Guardians of the Galaxy Vol. 3",
          video: false,
          vote_average: 8,
          vote_count: 4345,
        },
        {
          adult: false,
          backdrop_path: "/f7UI3dYpr7ZUHGo0iIr1Qvy1VPe.jpg",
          genre_ids: [16, 10751, 14, 35],
          id: 1040148,
          original_language: "en",
          original_title: "Ruby Gillman, Teenage Kraken",
          overview:
            "Ruby Gillman, a sweet and awkward high school student, discovers she's a direct descendant of the warrior kraken queens. The kraken are sworn to protect the oceans of the world against the vain, power-hungry mermaids. Destined to inherit the throne from her commanding grandmother, Ruby must use her newfound powers to protect those she loves most.",
          popularity: 673.691,
          poster_path: "/kgrLpJcLBbyhWIkK7fx1fM4iSvf.jpg",
          release_date: "2023-06-28",
          title: "Ruby Gillman, Teenage Kraken",
          video: false,
          vote_average: 7.6,
          vote_count: 543,
        },
        {
          adult: false,
          backdrop_path: "/lDCIQ1Qe7cRnhZ4ybQVVEbadMZ.jpg",
          genre_ids: [27, 53],
          id: 1008042,
          original_language: "en",
          original_title: "Talk to Me",
          overview:
            "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
          popularity: 665.969,
          poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
          release_date: "2023-07-26",
          title: "Talk to Me",
          video: false,
          vote_average: 7.1,
          vote_count: 192,
        },
      ],
      total_pages: 39614,
      total_results: 792276,
    };

    return mock.results.map(
      (d) =>
        new Movie(
          TmdbId.fromIdAndType(d.id.toString(), "movie"),
          d.adult,
          d.backdrop_path,
          d.original_language,
          d.original_title,
          d.overview,
          d.popularity,
          d.poster_path,
          d.release_date,
          d.title,
          d.video,
          d.vote_average,
          d.vote_count
        )
    );
  }
}
